name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.5.3
  file_picker: ^10.3.2
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  device_info_plus: ^10.1.2
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_form_builder: ^10.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.4.2
  form_builder_validators: ^11.2.0
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  provider: ^6.1.5+1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  shimmer: ^3.0.0
  firebase_core: ^4.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  sign_in_with_apple: ^6.1.0
  app_links: ^6.4.1
  webview_flutter: ^4.9.0
  cloud_firestore: ^6.1.0
  audioplayers: ^6.5.1
  pdf: ^3.10.4
  printing: ^5.11.1
  share_plus: ^10.0.0
  open_filex: ^4.5.0
  file_saver: ^0.2.14
  record: ^6.1.2
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  flutter_markdown: ^0.7.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/terms.txt
    - assets/general_conditions.txt
    - assets/privacy.txt
    - .env